### ISSUE TITLE
All keepass importers are broken

### ISSUE THREAD

**Issue by KD0BPV** [roddhjav/pass-import#11]
I've tried all the importers for importing from my keepass database, and they're all giving me language or execution errors. I am using exports from the appropriate program for each importer. 

keepass:
```
mark@Ares-Linux ~ % pass import keepass Database.xml   
Usage: /usr/lib/password-store/importers/keepass2pass.py -f XML_FILE
Optional:
 -r ROOT_PATH    Different root path to use than the one in xml file, use "" for none

mark@Ares-Linux ~ % pass import keepass -f Database.xml  
pass import: invalid option -- 'f'
pass import - A generic importer extension for pass

Vesion: 0.2

Usage:
    pass import <importer> [ARG]
        Import data to a password store.
        ARG depends of the importer script.
        <importer> can be: keepassx revelation roboform enpass pwsafe fpm chrome kwallet kedpm keepass password-exporter 1password lastpass keepass2csv gorilla

Options:
    -v, --version  Show version information.
    -h, --help     Print this help message and exit.

More information may be found in the pass-import(1) man page.
```
keepassx:
```
mark@Ares-Linux ~ % pass import keepassx database.csv
Traceback (most recent call last):
  File "/usr/lib/password-store/importers/keepassx2pass.py", line 83, in <module>
    main(sys.argv[1])
  File "/usr/lib/password-store/importers/keepassx2pass.py", line 79, in main
    for group in ElementTree.parse(xml_file).findall('group'):
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 7
```
keepass2csv:
```
mark@Ares-Linux ~ % pass import keepass2csv Database.csv 
File to read: Database.csv
Traceback (most recent call last):
  File "/usr/lib/password-store/importers/keepass2csv2pass.py", line 62, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/importers/keepass2csv2pass.py", line 59, in main
    readFile(inputFile)
  File "/usr/lib/password-store/importers/keepass2csv2pass.py", line 32, in readFile
    prepareForInsertion(row)
  File "/usr/lib/password-store/importers/keepass2csv2pass.py", line 42, in prepareForInsertion
    notes = row[5]
IndexError: list index out of range
```

**Comment by roddhjav** [comment]
Hi, thank for the feedback.

It's been a while but I want to let you know I'm aware of this issue and it will be fixed by the complete rewriting of `pass-import` that is almost ready.

See #15.
