### ISSUE TITLE
KeyError: 'path' on exportingn pass into csv

### ISSUE THREAD

**Issue by MsEleos** [roddhjav/pass-import#118]
So i used the example described in `man pimport` to create a csv file from my pass folder and received this error.
I'm using the git version of pimport

```
╭─skinnery at jessie in ~ 
╰─○ pimport csv ~/.password-store --out file.csv
  w  Unable to detect the pass format for /home/skinnery/.password-store, using the default pass importer
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/skinnery/.local/lib/python3.8/site-packages/pass_import/__main__.py", line 425, in <module>
    main()
  File "/home/skinnery/.local/lib/python3.8/site-packages/pass_import/__main__.py", line 417, in main
    paths = pass_export(conf, cls_export, data)
  File "/home/skinnery/.local/lib/python3.8/site-packages/pass_import/__main__.py", line 363, in pass_export
    pmpath = os.path.join(conf['droot'], entry['path'])
KeyError: 'path'
```

I scrolled through the issues and trying small things but nothing seems to change this error.
Thanks  in advance for any help

**Comment by roddhjav** [comment]
Hi, Thank a lot for this issue. That is a bad bug ;). It should be fixed with 9907d76.
