### ISSUE TITLE
Unable to import from lastpass

### ISSUE THREAD

**Issue by Duddino** [roddhjav/pass-import#119]
```Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/pass-import/pass-import/pass_import/__main__.py", line 426, in <module>
    main()
  File "/tmp/pass-import/pass-import/pass_import/__main__.py", line 417, in main
    data = pass_import(conf, cls_import)
  File "/tmp/pass-import/pass-import/pass_import/__main__.py", line 329, in pass_import
    importer.parse()
  File "/tmp/pass-import/pass-import/pass_import/managers/lastpass.py", line 28, in parse
    super(LastpassCSV, self).parse()
  File "/tmp/pass-import/pass-import/pass_import/formats/csv.py", line 43, in parse
    for row in self.reader:
  File "/usr/lib/python3.8/csv.py", line 111, in __next__
    row = next(self.reader)
_csv.Error: line contains NUL```

**Comment by roddhjav** [comment]
Can you provide the command you used and the header of your lastpass file?

**Comment by Duddino** [comment]
The header: `url,username,password,extra,name,grouping,fav`
The commands I tried are `pass import [file]` and `pass import lastpass [file]`

**Comment by elsauer** [comment]
Please tell me whether I should open a new issue or not! I am experiencing similar problems when trying to import from lastpass.
Importing the test file @roddhjav mentioned above works just fine. However when I encrypt it (with my own gpg-key), I get the following error:
```
pass import -vvv testfile.csv.gpg
  .  Trying to guess file format and manager name.
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/pass_import/__main__.py", line 435, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pass_import/__main__.py", line 420, in main
    cls_import = detectmanager(conf)
  File "/usr/lib/python3.9/site-packages/pass_import/__main__.py", line 297, in detectmanager
    pm = detect.manager(to_detect)
  File "/usr/lib/python3.9/site-packages/pass_import/auto.py", line 147, in manager
    if file.is_format():
  File "/usr/lib/python3.9/site-packages/pass_import/formats/xml.py", line 112, in is_format
    self.tree = ElementTree.XML(self.file.read())
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 0: invalid start byte
```

Version: pass import 3.1
OS: Arch Linux

**Comment by roddhjav** [comment]
Why do you want to encrypt the csv exported file before importing it?

Regarding the exception, that's a bug on the password manager format recognition. I will fix it thanks.

However, you can simply bypass this format recognition with: `pass import -vvv lastpass  testfile.csv.gpg`

**Comment by elsauer** [comment]
Lastpass does not support encrypted exporting afaik. That's why I piped it into `gpg` prior to importing it into `pass`. There may be a more elegant way to do this, that I am not aware of.

Unfortunately, I had not pulled any of those dependencies earlier. Installing `python-magic` solved my problem. There may be no bug after all…
Thank you for your patience!
