### ISSUE TITLE
Keepass import stopped working since pykeepass 3.2.1

### ISSUE THREAD

**Issue by aellwein** [roddhjav/pass-import#121]
Hi,

i tried today to run ``pass-import`` together with ``pykeepass`` (both installed by pip, pass-import==3.0 and pykeepass==3.2.1), but the import fails with following trace:

```
Traceback (most recent call last):
  File "/Users/alex/venvs/pass-import/.venv/lib/python3.8/site-packages/pass_import/__main__.py", line 328, in pass_import
    with cls_import(conf['in'], settings=settings) as importer:
  File "/Users/alex/venvs/pass-import/.venv/lib/python3.8/site-packages/pass_import/core.py", line 119, in __enter__
    self.open()
  File "/Users/alex/venvs/pass-import/.venv/lib/python3.8/site-packages/pass_import/formats/kdbx.py", line 134, in open
    raise ImportError(name='pykeepass')
ImportError
```
After some investigation, i found out that the import ``from pykeepass.exceptions import CredentialsIntegrityError`` fails
because there is no such class in pykeepass since last released version 3.2.1.

**Comment by roddhjav** [comment]
This is already fixed, but you should install pass-import from the master branch. I plan to release soon, but I clearly do not have the time at the moment.
