### ISSUE TITLE
import from `keepassxc` to `gopass` fails

### ISSUE THREAD

**Issue by thomas-mc-work** [roddhjav/pass-import#145]
I get this stack trace:

    Traceback (most recent call last):
      File "/home/thomas/.local/bin/pimport", line 8, in <module>
        sys.exit(main())
      File "/home/thomas/.local/lib/python3.8/site-packages/pass_import/__main__.py", line 430, in main
        data = pass_import(conf, cls_import)
      File "/home/thomas/.local/lib/python3.8/site-packages/pass_import/__main__.py", line 342, in pass_import
        importer.parse()
      File "/home/thomas/.local/lib/python3.8/site-packages/pass_import/formats/kdbx.py", line 138, in parse
        history = self._getentry(hentry)
      File "/home/thomas/.local/lib/python3.8/site-packages/pass_import/formats/kdbx.py", line 62, in _getentry
        value = self._subref(value)
      File "/home/thomas/.local/lib/python3.8/site-packages/pass_import/formats/kdbx.py", line 115, in _subref
        kpentry = self.keepass.find_entries(uuid=uuid.UUID(attid))[0]
    IndexError: list index out of range

This used to work fine after my own PR for gopass. Maybe it's related to https://github.com/roddhjav/pass-import/pull/132?

Sadly I failed to reconstruct the same situation with PyCharm. With the IDE I always get this error:

    Traceback (most recent call last):
      File "<input>", line 3, in <module>
      File "/home/thomas/.local/opt/pycharm-community-2020.2.3/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
        pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
      File "/home/thomas/.local/opt/pycharm-community-2020.2.3/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
        exec(compile(contents+"\n", file, 'exec'), glob, loc)
      File "/home/thomas/work/workspace/python/pass-import/pass_import/__main__.py", line 438, in <module>
        main()
      File "/home/thomas/work/workspace/python/pass-import/pass_import/__main__.py", line 430, in main
        data = pass_import(conf, cls_import)
      File "/home/thomas/work/workspace/python/pass-import/pass_import/__main__.py", line 341, in pass_import
        with cls_import(conf['in'], settings=settings) as importer:
      File "/home/thomas/work/workspace/python/pass-import/pass_import/core.py", line 118, in __enter__
        self.open()
      File "/home/thomas/work/workspace/python/pass-import/pass_import/formats/kdbx.py", line 207, in open
        self.keepass = PyKeePass(self.prefix,
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 65, in __init__
        self.read(
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/pykeepass/pykeepass.py", line 103, in read
        self.kdbx = KDBX.parse_file(
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 309, in parse_file
        return self.parse_stream(f, **contextkw)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 300, in parse_stream
        return self._parsereport(stream, context, "(parsing)")
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
        obj = self._parse(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 1982, in _parse
        subobj = sc._parsereport(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
        obj = self._parse(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 2440, in _parse
        return self.subcon._parsereport(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
        obj = self._parse(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 4266, in _parse
        obj = self.subcon._parsereport(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
        obj = self._parse(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 1982, in _parse
        subobj = sc._parsereport(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
        obj = self._parse(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 2440, in _parse
        return self.subcon._parsereport(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 312, in _parsereport
        obj = self._parse(stream, context, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 841, in _parse
        return stream_read(stream, length, path)
      File "/home/thomas/work/workspace/python/pass-import/venv/lib/python3.8/site-packages/construct/core.py", line 92, in stream_read
        raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
    construct.core.StreamError: Error in path (parsing) -> header -> magic1
    stream read less than specified amount, expected 4, found 0

**Comment by roddhjav** [comment]
This might indeed be an issue with the reference substitution. I will have to test it better.
