### ISSUE TITLE
Bitwarden JSON import broken

### ISSUE THREAD

**Issue by adworacz** [roddhjav/pass-import#147]
1. Installed `pass-import` from the AUR.
2. Ran `pass import -vvv bitwarden bitwarden_export_date.json`.
3. Output:
```
  .  Trying to guess file format.
  .  Importer: bitwarden, Format: csv, Version:
  .  Importing passwords from BitwardenCSV to PasswordStore
  .  Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pass_import/__main__.py", line 342, in pass_import
    importer.parse()
  File "/usr/lib/python3.9/site-packages/pass_import/formats/csv.py", line 40, in parse
    raise FormatError()
pass_import.errors.FormatError
```

In short, the JSON file is being detected as a CSV. I've opened the file - it's definitely JSON.

Edit: Version is 3.2:
```
~ >>> pacman -Qs pass-import
local/pass-import 3.2-1
    A pass extension for importing data from most of the existing password manager.
```

**Comment by adworacz** [comment]
Hmmm, this might be a false alarm. My Bitwarden install looks a little out of date, let me update it and try again.

**Comment by adworacz** [comment]
Yup - false alarm. My bitwarden install was out of date. Sorry for the churn, closing.
