### ISSUE TITLE
pass import freezes

### ISSUE THREAD

**Issue by helionmelion** [roddhjav/pass-import#164]
Hello, I'm having this problem here on my arch linux. The script freezes without nothing imported and after ctrl+c (I have to abort) this is what is shown:

% pass import keepass.kdbx -vvv                        
  .  Trying to guess file format and manager name.
  .  Importer: keepassxc, Format: kdbx, Version: 
  .  Importing passwords from KeepassxcKDBX to PasswordStore
Password for keepass.kdbx: 
^CTraceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/pass_import/__main__.py", line 438, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pass_import/__main__.py", line 431, in main
    paths = pass_export(conf, cls_export, data)
  File "/usr/lib/python3.10/site-packages/pass_import/__main__.py", line 374, in pass_export
    exporter.clean(conf['clean'], conf['convert'])
  File "/usr/lib/python3.10/site-packages/pass_import/manager.py", line 163, in clean
    clean.duplicate(self.data)
  File "/usr/lib/python3.10/site-packages/pass_import/clean.py", line 131, in duplicate
    if re.search(r'%s(\d+)$' % SEPARATOR, path) is None:
  File "/usr/lib/python3.10/re.py", line 197, in search
    def search(pattern, string, flags=0):
KeyboardInterrupt

Already reinstalled it. Tried other ways like importing csv, json, from enpass, nothing works. I feel there is some python incompatibility in course here. In the past, pass import worked very well. Could I have some light here. Thank you very much.

**Comment by roddhjav** [comment]
As python 3.10 has just been released on arch, you might need to rebuild the package (if you installed it from the AUR). Otherwise, I have run the test suite on arch with python 3.10 and everything is fine, so you can try it from source by cloning the master branch.

**Comment by helionmelion** [comment]
I removed the previously installed pass import from arch linux package manager (yay - pacman) and reinstalled from source as indicated. Now It worked flawlessly. Thank you very much sir.
