### ISSUE TITLE
import.py line 649 tracebacks

### ISSUE THREAD

**Issue by morpheuskafka** [roddhjav/pass-import#21]
Observed with AUR and git clone. Appears with type `keepassxc` or `keepasscsv`:

```
[rocket@halfworld ~]$ pass import keepasscsv passwords_unecrypted.csv
Traceback (most recent call last):
  File "/usr/lib/password-store/import/import.py", line 649, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/import/import.py", line 608, in main
    importer.parse(file)
  File "/usr/lib/password-store/import/import.py", line 279, in parse
    self._checkformat(reader.fieldnames)
  File "/usr/lib/password-store/import/import.py", line 274, in _checkformat
    raise FormatError()
import.FormatError
```

```
[rocket@halfworld ~]$ pass import keepassxc /keybase/public/morpheuskafka/encrypted/vault.kdbx
Traceback (most recent call last):
  File "/usr/lib/password-store/import/import.py", line 649, in <module>
    main(sys.argv)
  File "/usr/lib/password-store/import/import.py", line 608, in main
    importer.parse(file)
  File "/usr/lib/password-store/import/import.py", line 279, in parse
    self._checkformat(reader.fieldnames)
  File "/usr/lib/python3.6/csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9a in position 3: invalid start byte
```

**Comment by roddhjav** [comment]
Hi,

Regarding your error with `keepasscsv`, you should have seen an error like:
```
[x] Error: passwords_unecrypted.csv is not a exported keepasscsv file
```
I don't know why the exception was not handle correctly.
Can you give me more details like: 
* The header of your csv file.
* The version of keepass used to export the csv file.

Regarding `keepassxc` its because you are trying to import the encrypted database. You should export the database in a plain csv file before.

**Comment by morpheuskafka** [comment]
D'oh! I wass trying to import the KeePassXC exported CSV using the `keepasscsv` type and the encrypted file using the `keepassxc` type. When I ran `pass import keepassxc passwords_unecrypted.csv` it worked perfectly! Thanks!
