### ISSUE TITLE
AUR package broken

### ISSUE THREAD

**Issue by pulpocaminante** [roddhjav/pass-import#219]
Fresh install of pass-import from the AUR results in:

```
amnesia git:master*  
❯ pass import
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/lib/python3.11/site-packages/pass_import/__init__.py", line 11, in <module>
    import pass_import.formats  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pass_import/formats/__init__.py", line 1, in <module>
    from pass_import.formats.csv import CSV
  File "/usr/lib/python3.11/site-packages/pass_import/formats/csv.py", line 12, in <module>
    from pass_import.manager import PasswordImporter
  File "/usr/lib/python3.11/site-packages/pass_import/manager.py", line 11, in <module>
    from pass_import.audit import Audit
  File "/usr/lib/python3.11/site-packages/pass_import/audit.py", line 9, in <module>
    from zxcvbn import zxcvbn
ModuleNotFoundError: No module named 'zxcvbn'
```

Nothing unusual:

```
amnesia git:master*                                                                                                     /3.1s
❯ pacman -Ss zxcvbn
extra/python-zxcvbn 4.4.28-4 [installed]
```

Python versioning error

**Comment by roddhjav** [comment]
Should be fixed on the AUR now (it only require a rebuild of the package to the latest python version).
