### ISSUE TITLE
Add Enpass 6 support

### ISSUE THREAD

**Issue by chrkl** [roddhjav/pass-import#72]
Enpass dropped csv export in version 6. Available export options are now txt or json.

**Comment by roddhjav** [comment]
Hi, thank for this catch. I added the support for `enpass6` with 9c635dabc6ed4a34550905e59131497839aafb3d

**Comment by chrkl** [comment]
Awesome! Thank you for the quick solution.

**Comment by chrkl** [comment]
The import fails for me because my JSON export does not contain folders:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 925, in <module>
    main(sys.argv)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 889, in main
    importer.parse(file)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 538, in parse
    for item in jsons['folders']:
KeyError: 'folders'

**Comment by chrkl** [comment]
Sorry to bother you again. I also have no folder references in the item list:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 925, in <module>
    main(sys.argv)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 889, in main
    importer.parse(file)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 546, in parse
    entry['group'] = item['folders'][0]
KeyError: 'folders'

**Comment by roddhjav** [comment]
Yes, I saw this just after my last push. This, already fixed and (force) pushed.

**Comment by chrkl** [comment]
Still no success:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 925, in <module>
    main(sys.argv)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 889, in main
    importer.parse(file)
  File "/usr/lib/python3.7/site-packages/pass_import.py", line 546, in parse
    entry['group'] = item.get('folders', [])[0]
IndexError: list index out of range

**Comment by roddhjav** [comment]
Yes, that because I am stupid ;). Fixed now.

**Comment by chrkl** [comment]
Works now ;-) Thanks again for the quick fix!
